### ISSUE TITLE
Great scaler!  However, there is a significant shift towards magenta with each loop.

### ISSUE THREAD

**Issue by sedetweiler** [Elldreth/loopback_scaler#1]
Are you also seeing this, as I have many examples of this occurring on 1.5 DDIM?

**Comment by Elldreth** [comment]
I'll have to dig into the issue.  If it's a problem with the sampler we can test with other samplers.  Also, this looper is something you can do manually.  I'll take some time this weekend and see if I can figure out if it's sampler based.

**Comment by Elldreth** [comment]
I tested this weekend and I do not see a significant shift towards magenta each loop, but that likely has more to do with model used and sampler than the looper code specifically.  The Loopback Scaler just takes a source image and increases the size by an amount divided by the target size and the number of loops.  Once an image is generated using img2img, the resulting image is then set as the source for the next loop.  So, the Loopback Scaler script doesn't do anything to the image, it just uses the A1111 framework to continually generate images and feed them back in for another loop.

If this is something you are still struggling with, please let me know what models you are using and share some examples.
