### ISSUE TITLE
is it possible to use controlNET's tile model?

### ISSUE THREAD

**Issue by Rkkss** [Elldreth/loopback_scaler#14]
Title. 
ControlNET now support imaged loopback, I assume it's technically possible.

**Comment by Elldreth** [comment]
I've been playing around with the CN tile model (and tile resample preproc) to see how this might benefit a post process workflow.  More to come on this.

**Comment by Elldreth** [comment]
You can use the CN Tile model.  I'm sure it isn't setup to work most efficiently though.  I'm revamping the loopback code now and incorporating a lot of new ideas into it.  I'll consider CN Tile as part of the design.
