### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by zArvin6808** [Elldreth/loopback_scaler#15]
TypeError: Script.run() missing 15 required positional arguments: 'frames', 'denoising_strength_change_amplitude', 'frames_per_wave', 'denoising_strength_change_offset', 'initial_image_number', 'prompts', 'save_prompts', 'save_video', 'output_dir', 'video_fps', 'video_quality', 'video_encoding', 'ffmpeg_path', 'segment_video', and 'video_segment_duration'
Time taken: 0.00sTorch active/reserved: 2076/2088 MiB, Sys VRAM: 3965/8192 MiB (48.4%)

**Comment by Elldreth** [comment]
I've not seen this error before.  It looks like it has something to do with an extension or module that is related to video creation.  loopback_scaler doesn't interface with ffmpeg on its own.  If you are trying to use loopback scaler with something like deforum, let me know and I can have a look.  Can you give more context?
