### ISSUE TITLE
error report when launch weibui: loopback_scaler.py", line 86, SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by SkyKn1ght** [Elldreth/loopback_scaler#3]
error report when launch weibui, like this:

Error loading script: loopback_scaler.py
Traceback (most recent call last):
...
stable-diffusion-webui\scripts\loopback_scaler.py", line 86
    <title>loopback_scaler/loopback_scaler.py at main · Elldreth/loopback_scaler</title>
                                                      ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by Elldreth** [comment]
That's very odd.  I haven't been able to reproduce this yet.  I also updated my a1111 install to the latest version and reloaded with no issues.  Has it always done this or are you just now seeing this error (and it wasn't doing this before)?

**Comment by vw1693** [comment]
It oly happens if you instal Manual.
If you instal it from the webui it works fine.
