### ISSUE TITLE
Batch Mode with Embedded Prompts

### ISSUE THREAD

**Issue by gobshyte** [Elldreth/loopback_scaler#5]
Hi

Probably a feature request, but is it possible to use this in batch mode? Eg. I would love to be able to point it at a folder of images and for it to use the embedded prompts in the images. 

My understanding is you can only use this script with one image at a time and you have to manually input the prompt (or send img+prompt manually) one at a time, it cannot be used in batch mode properly?

**Comment by gobshyte** [comment]
Note there is some similar scripting here which can be used with hiresfix/sdupscale batches, reading prompts from file, but I don't think we can use in combination with this script

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4938

**Comment by Elldreth** [comment]
Thanks for the idea.. been having dreams about this one actually :D  I started working on this project with the idea of creating a batch image processor.  I'm not sure this will make it in the next version but it's in the plan.

**Comment by Elldreth** [comment]
A1111 has a batch mode that works with the looper now.  This issue is closed.
